name: Hello
on: push
defaults:
  run:
    shell: bash
jobs:
  hello:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello, world"
          echo "::debug::これはデバッグ用です"
      - uses: actions/checkout@v7
