name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  print:
    name: 表示
    runs-on: ubuntu-latest
    steps:
      - name: 実行ステップ
        run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NULL: ${{ null }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_NUMBER: ${{ 1234 }}
          LITERAL_STRING: ${{ 'Hello' }}
          LITERAL_OMIT_STRING: World
  custom-run:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${{ inputs.greeting }}"
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1}${PASSWORD#?}"

